/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    staff: StaffAuthOperations;
  };
  blocks: {};
  collections: {
    articles: Article;
    destinations: Destination;
    topics: Topic;
    authors: Author;
    staff: Staff;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    destinations: DestinationsSelect<false> | DestinationsSelect<true>;
    topics: TopicsSelect<false> | TopicsSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    staff: StaffSelect<false> | StaffSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Staff;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface StaffAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: string;
  title: string;
  /**
   * One or two sentences under the title.
   */
  deck: string;
  /**
   * Short summary used on article cards.
   */
  excerpt: string;
  /**
   * Optional summary box at the top of the article.
   */
  takeaways?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  body: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Itineraries only: one entry per day.
   */
  days?:
    | {
        title: string;
        stops?:
          | {
              /**
               * For example 8:30 am.
               */
              time?: string | null;
              name: string;
              note?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  disclosure: {
    kind: 'none' | 'affiliate' | 'sponsored';
    sponsorName?: string | null;
  };
  adPolicy: 'standard' | 'none';
  seo: {
    /**
     * Title shown in search results. Aim for about 50 to 60 characters.
     */
    title: string;
    /**
     * Summary shown in search results. Aim for about 140 to 160 characters.
     */
    description: string;
    /**
     * Tick to ask search engines not to index this page.
     */
    noindex?: boolean | null;
  };
  /**
   * Used in the article address: /stories/your-slug
   */
  slug: string;
  type:
    | 'destination-guide'
    | 'itinerary'
    | 'practical-advice'
    | 'gear-review'
    | 'photo-essay'
    | 'video-story'
    | 'sponsored-feature';
  /**
   * Workflow stage. Approving needs an editor. Publishing needs a publisher and uses the Publish button.
   */
  editorialState: 'draft' | 'in-review' | 'approved' | 'archived';
  primaryAuthor: string | Author;
  coauthors?: (string | Author)[] | null;
  /**
   * Used for breadcrumbs and the destination hub.
   */
  primaryDestination?: (string | null) | Destination;
  additionalDestinations?: (string | Destination)[] | null;
  topics?: (string | Topic)[] | null;
  /**
   * Set automatically on first publication.
   */
  firstPublishedAt?: string | null;
  /**
   * Set only for a real content update, not a typo fix.
   */
  editorialUpdatedAt?: string | null;
  /**
   * Last time prices, transport and opening details were checked.
   */
  reviewedAt?: string | null;
  createdBy?: (string | null) | Staff;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: string;
  name: string;
  /**
   * Used in the author page address: /authors/your-slug
   */
  slug: string;
  /**
   * Short public biography.
   */
  biography: string;
  /**
   * First-hand travel or subject experience that supports this author’s articles.
   */
  relevantExperience?: string | null;
  /**
   * Verified external profiles only.
   */
  links?:
    | {
        label: string;
        url: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations".
 */
export interface Destination {
  id: string;
  name: string;
  /**
   * One URL segment only, for example "kyoto". The full path is built from the parent.
   */
  slug: string;
  kind: 'country' | 'region' | 'city';
  /**
   * Leave empty for a country.
   */
  parent?: (string | null) | Destination;
  /**
   * Canonical path under /destinations/. Set automatically when saved.
   */
  path?: string | null;
  /**
   * Optional. Two-letter ISO country code, for example JP.
   */
  isoCountryCode?: string | null;
  /**
   * Optional. Destination signature colour. It must be dark enough for light text.
   */
  accentColour?: string | null;
  /**
   * One or two sentences used on cards and at the top of the hub.
   */
  summary: string;
  /**
   * Original introduction, best-time guidance and practical notes.
   */
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  seo: {
    /**
     * Title shown in search results. Aim for about 50 to 60 characters.
     */
    title: string;
    /**
     * Summary shown in search results. Aim for about 140 to 160 characters.
     */
    description: string;
    /**
     * Tick to ask search engines not to index this page.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics".
 */
export interface Topic {
  id: string;
  name: string;
  /**
   * Used in the topic page address: /topics/your-slug
   */
  slug: string;
  /**
   * Original introduction for the topic page.
   */
  introduction: string;
  /**
   * Optional. Articles to feature at the top of this topic page.
   */
  featuredArticles?: (string | Article)[] | null;
  seo: {
    /**
     * Title shown in search results. Aim for about 50 to 60 characters.
     */
    title: string;
    /**
     * Summary shown in search results. Aim for about 140 to 160 characters.
     */
    description: string;
    /**
     * Tick to ask search engines not to index this page.
     */
    noindex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff".
 */
export interface Staff {
  id: string;
  name: string;
  /**
   * Contributor: own drafts. Editor: edits and reviews all content. Publisher: publishes and withdraws. Administrator: manages staff and settings.
   */
  role: 'contributor' | 'editor' | 'publisher' | 'administrator';
  /**
   * Untick to suspend this account without deleting it.
   */
  active?: boolean | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'staff';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'articles';
        value: string | Article;
      } | null)
    | ({
        relationTo: 'destinations';
        value: string | Destination;
      } | null)
    | ({
        relationTo: 'topics';
        value: string | Topic;
      } | null)
    | ({
        relationTo: 'authors';
        value: string | Author;
      } | null)
    | ({
        relationTo: 'staff';
        value: string | Staff;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'staff';
    value: string | Staff;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'staff';
    value: string | Staff;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  title?: T;
  deck?: T;
  excerpt?: T;
  takeaways?:
    | T
    | {
        text?: T;
        id?: T;
      };
  body?: T;
  days?:
    | T
    | {
        title?: T;
        stops?:
          | T
          | {
              time?: T;
              name?: T;
              note?: T;
              id?: T;
            };
        id?: T;
      };
  disclosure?:
    | T
    | {
        kind?: T;
        sponsorName?: T;
      };
  adPolicy?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        noindex?: T;
      };
  slug?: T;
  type?: T;
  editorialState?: T;
  primaryAuthor?: T;
  coauthors?: T;
  primaryDestination?: T;
  additionalDestinations?: T;
  topics?: T;
  firstPublishedAt?: T;
  editorialUpdatedAt?: T;
  reviewedAt?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "destinations_select".
 */
export interface DestinationsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  kind?: T;
  parent?: T;
  path?: T;
  isoCountryCode?: T;
  accentColour?: T;
  summary?: T;
  body?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "topics_select".
 */
export interface TopicsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  introduction?: T;
  featuredArticles?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        noindex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  biography?: T;
  relevantExperience?: T;
  links?:
    | T
    | {
        label?: T;
        url?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "staff_select".
 */
export interface StaffSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  active?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}